# Generated by Django 6.0.5 on 2026-05-19 08:10

from django.db import migrations


def create_autores_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Artigo = apps.get_model('artigos', 'Artigo')

    group, created = Group.objects.get_or_create(name='autores')
    
    content_type = ContentType.objects.get_for_model(Artigo)
    permissions = Permission.objects.filter(content_type=content_type)
    
    for perm in permissions:
        group.permissions.add(perm)

class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.RunPython(create_autores_group),
    ]
