# Generated by Django 6.0.5 on 2026-05-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("artigos", "0002_create_autores_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="artigo",
            name="likes_anonimos",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
