# Generated by Django 5.2.13 on 2026-04-11 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0004_remove_docente_linkedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='uc',
            new_name='unidade_curricular',
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='instituicao',
            field=models.CharField(default='Universidade Lusófona', max_length=200),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='licenciatura',
            name='codigo',
            field=models.PositiveIntegerField(default=260, unique=True),
        ),
        migrations.AlterField(
            model_name='unidadecurricular',
            name='licenciatura',
            field=models.ForeignKey(default=260, on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portefolio_app.licenciatura'),
        ),
    ]
