# Generated by Django 5.2.13 on 2026-04-11 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0006_licenciatura_lic_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='licenciatura',
            name='logo',
        ),
        migrations.AddField(
            model_name='licenciatura',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
