# Generated by Django 5.2.13 on 2026-04-11 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0007_remove_licenciatura_logo_licenciatura_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licenciatura',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
