# Generated by Django 5.2.13 on 2026-04-11 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0008_alter_licenciatura_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competencia',
            name='nome',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='formacao',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
