# Generated by Django 5.2.13 on 2026-04-10 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('link_pagina_pessoal', models.URLField(blank=True, null=True, verbose_name='Página Pessoal (Lusófona)')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='docentes/', verbose_name='Foto')),
            ],
        ),
        migrations.CreateModel(
            name='Formacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('instituicao', models.CharField(max_length=150)),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('certificado', models.FileField(blank=True, null=True, upload_to='formacoes/')),
            ],
            options={
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Licenciatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_anos', models.PositiveIntegerField(default=3)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='licenciatura/')),
            ],
        ),
        migrations.CreateModel(
            name='MakingOf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('data', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='makingof/')),
                ('entidade_relacionada', models.CharField(max_length=100)),
                ('justificacao', models.TextField(blank=True)),
                ('erro_correcao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='tecnologias/')),
                ('site_oficial', models.URLField(blank=True)),
                ('descricao', models.TextField(blank=True)),
                ('nivel_interesse', models.PositiveIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TFC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('alunos', models.CharField(max_length=300)),
                ('orientador', models.CharField(max_length=200)),
                ('ano', models.IntegerField(default=2025)),
                ('licenciatura', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('descricao', models.TextField()),
                ('palavras_chave', models.TextField()),
                ('areas', models.TextField()),
                ('tecnologias_usadas', models.TextField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='tfc/')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('objetivo', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='projetos/')),
                ('video_demo', models.URLField(blank=True)),
                ('github', models.URLField(blank=True)),
                ('tecnologias', models.ManyToManyField(to='portefolio_app.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='Competencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True)),
                ('nivel', models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Intermédio'), (3, 'Avançado')], default=2)),
                ('formacoes', models.ManyToManyField(blank=True, to='portefolio_app.formacao')),
                ('projetos', models.ManyToManyField(blank=True, to='portefolio_app.projeto')),
                ('tecnologias', models.ManyToManyField(blank=True, to='portefolio_app.tecnologia')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeCurricular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('ano', models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3)])),
                ('semestre', models.PositiveIntegerField(choices=[(1, 1), (2, 2)])),
                ('ects', models.PositiveIntegerField(default=6)),
                ('descricao', models.TextField(blank=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='ucs/')),
                ('docentes', models.ManyToManyField(related_name='ucs', to='portefolio_app.docente')),
                ('licenciatura', models.ForeignKey(default='Engenharia Informatica', on_delete=django.db.models.deletion.CASCADE, related_name='ucs', to='portefolio_app.licenciatura')),
            ],
        ),
        migrations.AddField(
            model_name='projeto',
            name='uc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portefolio_app.unidadecurricular'),
        ),
    ]
