# Generated by Django 5.2.13 on 2026-04-10 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='docentes/'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='link_pagina_pessoal',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='docente',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
