# Generated by Django 5.2.13 on 2026-04-10 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0002_alter_docente_email_alter_docente_foto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='link_pagina_pessoal',
        ),
        migrations.AddField(
            model_name='docente',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='docente',
            name='pagina_pessoal',
            field=models.URLField(blank=True),
        ),
    ]
