# Generated by Django 5.2.13 on 2026-04-11 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0003_remove_docente_link_pagina_pessoal_docente_linkedin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='linkedin',
        ),
    ]
