# Generated by Django 5.2.13 on 2026-04-11 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portefolio_app', '0005_rename_uc_projeto_unidade_curricular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenciatura',
            name='lic_link',
            field=models.URLField(default='https://www.ulusofona.pt/lisboa/licenciaturas/engenharia-informatica'),
        ),
    ]
