# Generated by Django 6.0.5 on 2026-05-19 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portefolio_app",
            "0009_alter_competencia_nome_alter_formacao_titulo_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="projeto",
            name="github",
            field=models.CharField(
                blank=True, help_text="Link para o repositório GitHub", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="video_demo",
            field=models.CharField(
                blank=True,
                help_text="Link para o vídeo de demonstração (ex: YouTube)",
                max_length=500,
            ),
        ),
    ]
