# Generated by Django 6.0.5 on 2026-05-19 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portefolio_app", "0010_alter_projeto_github_alter_projeto_video_demo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaTecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="aspectos_negativos",
            field=models.TextField(blank=True, help_text="Aspetos que não gostou"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="aspectos_positivos",
            field=models.TextField(blank=True, help_text="Aspetos que gostou"),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="categoria",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(
                blank=True, help_text="O que esta tecnologia faz e permite"
            ),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="categoria_relacionada",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tecnologias",
                to="portefolio_app.categoriatecnologia",
            ),
        ),
    ]
